services:
  postgres:
    image: postgres:16
    container_name: scheduler2_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    volumes:
      - scheduler2_postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: scheduler2-be:latest
    container_name: scheduler2_backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://scheduler2_postgres:5432/app_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
    ports:
      - "9267:8080"
    depends_on:
      - postgres

volumes:
  scheduler2_postgres_data:
